user:
  name:
    max_length: 50
  email:
    max_length: 127
  password:
    min_length: 8
  gravatar:
    size_30: 30
    size_50: 50
    size_80: 80
  per_page: 20
micropost:
  content:
    max_length: 140
  per_page: 20
seed:
  user:
    number_fake_users: 99
  micropost:
    number_fake_microposts: 50
feed:
  per_page: 10
following:
  per_page: 20
follower:
  per_page: 20
